pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test
#services
services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=myapp
